asset_path: /home/wanjunkim/ARSL/regrind-upload/USD/n_wc_v3_temp.stl
usd_dir: /home/wanjunkim/ARSL/regrind-upload/USD/revo2_vertical_adapter
usd_file_name: revo2_vertical_adapter.usd
force_usd_conversion: true
make_instanceable: false
mass_props: null
rigid_props: null
collision_props:
  collision_enabled: true
  contact_offset: null
  rest_offset: null
  torsional_patch_radius: null
  min_torsional_patch_radius: null
  _usd_applied_schema: PhysxCollisionAPI
  _usd_field_exceptions:
    PhysxCollisionAPI: !!python/tuple
    - physxCollision
    - - contact_offset
      - rest_offset
  _usd_namespace: physxCollision
mesh_collision_props:
  mesh_approximation_name: convexHull
  hull_vertex_limit: null
  min_thickness: null
  _usd_applied_schema: PhysxConvexHullCollisionAPI
  _usd_attr_name_map: {}
  _usd_field_exceptions: {}
  _usd_namespace: physxConvexHullCollision
translation: !!python/tuple
- 0.0
- 0.0
- 0.0
rotation: !!python/tuple
- 0.0
- 0.0
- 0.0
- 1.0
scale: !!python/tuple
- 1.0
- 1.0
- 1.0
##
# Generated by MeshConverter on 2026-09-04 at 15:37:51.
##
