"""Floating-base Revo2 right-hand asset for REGRIND training."""

from __future__ import annotations

import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets import ArticulationCfg

from regrind.assets import REGRIND_PROJECT_ROOT
from regrind.data.rb3_revo2_reference import REVO2_JOINT_NAMES
from regrind.robots.rb3_revo2 import REVO2_FOLLOWER_JOINTS


FREE_REVO2_USD_PATH = REGRIND_PROJECT_ROOT / "USD" / "revo2_floating.usda"
REVO2_ALL_JOINT_NAMES = REVO2_JOINT_NAMES + tuple(REVO2_FOLLOWER_JOINTS)
REVO2_FINGERTIP_BODY_NAMES = (
    "right_thumb_touch_link",
    "right_index_touch_link",
    "right_middle_touch_link",
    "right_ring_touch_link",
    "right_pinky_touch_link",
)

# Keep the same physical baseline as the assembled RB3+Revo2 task. Only the
# six leader joints are policy-controlled; follower targets are generated by
# the Revo2 residual action term.
_STIFFNESS = {name: 3.0 for name in REVO2_ALL_JOINT_NAMES}
_DAMPING = {name: 0.1 for name in REVO2_ALL_JOINT_NAMES}
_EFFORT = {name: 0.5 for name in REVO2_ALL_JOINT_NAMES}


FREE_REVO2_RIGHT_HAND_CFG = ArticulationCfg(
    # The overlay's default prim is composed directly onto the spawn prim.
    # Let Isaac Lab discover its single ArticulationRootAPI at that location.
    articulation_root_prim_path=None,
    spawn=sim_utils.UsdFileCfg(
        usd_path=str(FREE_REVO2_USD_PATH),
        joint_drive_props=sim_utils.JointDrivePropertiesCfg(
            drive_type="force",
            max_velocity=1000.0,
        ),
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            # The floating root is controlled by Cartesian impedance, matching
            # the public REGRIND Leap/Wuji tasks. Object gravity stays enabled.
            disable_gravity=True,
            max_depenetration_velocity=5.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            fix_root_link=False,
            enabled_self_collisions=False,
            solver_position_iteration_count=32,
            solver_velocity_iteration_count=2,
            sleep_threshold=0.005,
            stabilization_threshold=0.0005,
        ),
    ),
    actuators={
        "revo2_hand": ImplicitActuatorCfg(
            joint_names_expr=list(REVO2_ALL_JOINT_NAMES),
            stiffness=_STIFFNESS,
            damping=_DAMPING,
            effort_limit_sim=_EFFORT,
            velocity_limit_sim=100.0,
        ),
    },
    init_state=ArticulationCfg.InitialStateCfg(
        joint_pos={name: 0.0 for name in REVO2_ALL_JOINT_NAMES},
    ),
    soft_joint_pos_limit_factor=1.0,
)


# Policy residual scales before multiplication by the 30 Hz control period.
REVO2_RELATIVE_ACTION_SCALE = {r"^right_.*_joint$": 3.2}
